'use strict';

const { AGENTS } = require('./detect');

const THEMES = {
  dark: {
    bg: '#0d1117', surface: '#161b22', ink: '#e6edf3', muted: '#8b949e',
    rule: '#30363d', accent: '#58a6ff', accent2: '#3fb950'
  },
  light: {
    bg: '#ffffff', surface: '#f6f8fa', ink: '#1f2328', muted: '#656d76',
    rule: '#d0d7de', accent: '#0969da', accent2: '#1a7f37'
  }
};

const GRADE_COLORS = { S: '#e3b341', A: '#3fb950', B: '#58a6ff', C: '#8b949e' };

const SANS = "'Segoe UI', 'Helvetica Neue', Arial, 'PingFang SC', sans-serif";
const MONO = "'SFMono-Regular', Consolas, 'Courier New', monospace";

const COLOR_BY_ID = {};
for (const a of AGENTS) COLOR_BY_ID[a.id] = a.color;

function esc(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function fmt(n) {
  return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

function trunc(s, n) {
  return s.length > n ? s.slice(0, n - 1) + '…' : s;
}

function shortDate(iso) {
  return iso ? String(iso).slice(0, 10) : '';
}

function emptyCard(t, stats) {
  const W = 800;
  const H = 200;
  const p = [];
  p.push('<svg xmlns="http://www.w3.org/2000/svg" width="' + W + '" height="' + H + '" viewBox="0 0 ' + W + ' ' + H + '" font-family="' + SANS + '">');
  p.push('<rect x="0.5" y="0.5" width="' + (W - 1) + '" height="' + (H - 1) + '" rx="12" fill="' + t.bg + '" stroke="' + t.rule + '"/>');
  p.push('<text x="40" y="50" font-size="20" font-weight="700" fill="' + t.ink + '">AI AGENT RÉSUMÉ</text>');
  p.push('<text x="760" y="50" font-size="12" font-family="' + MONO + '" fill="' + t.accent + '" text-anchor="end">' + esc(trunc(stats.repo || 'repo', 28)) + '</text>');
  p.push('<line x1="40" y1="70" x2="760" y2="70" stroke="' + t.rule + '"/>');
  p.push('<text x="400" y="112" font-size="16" font-weight="600" fill="' + t.ink + '" text-anchor="middle">No AI agent activity detected</text>');
  p.push('<text x="400" y="138" font-size="12" fill="' + t.muted + '" text-anchor="middle">' + fmt(stats.totalCommits) + ' human commits scanned. Your agents are still unemployed.</text>');
  p.push('<text x="400" y="170" font-size="10" fill="' + t.muted + '" text-anchor="middle">generated by agentsume · github.com/fzs356113-oss/agentsume</text>');
  p.push('</svg>');
  return p.join('\n');
}

function renderCard(stats, opts) {
  opts = opts || {};
  const t = THEMES[opts.theme] || THEMES.dark;
  if (stats.aiCommits === 0) return emptyCard(t, stats);

  const W = 800;
  const H = 480;
  const agents = stats.agents.slice(0, 5);
  const p = [];

  p.push('<svg xmlns="http://www.w3.org/2000/svg" width="' + W + '" height="' + H + '" viewBox="0 0 ' + W + ' ' + H + '" font-family="' + SANS + '">');
  p.push('<rect x="0.5" y="0.5" width="' + (W - 1) + '" height="' + (H - 1) + '" rx="12" fill="' + t.bg + '" stroke="' + t.rule + '"/>');

  p.push('<text x="40" y="50" font-size="20" font-weight="700" fill="' + t.ink + '">AI AGENT RÉSUMÉ</text>');
  p.push('<text x="760" y="50" font-size="12" font-family="' + MONO + '" fill="' + t.accent + '" text-anchor="end">' + esc(trunc(stats.repo || 'repo', 28)) + '</text>');
  p.push('<text x="40" y="70" font-size="11" fill="' + t.muted + '">' + esc(fmt(stats.aiCommits) + ' AI-assisted commits · ' + fmt(stats.totalCommits) + ' total · ' + shortDate(stats.firstDate) + ' → ' + shortDate(stats.lastDate)) + '</text>');
  p.push('<line x1="40" y1="84" x2="760" y2="84" stroke="' + t.rule + '"/>');

  const statDefs = [
    [fmt(stats.aiCommits), 'AI COMMITS'],
    [fmt(stats.aiLines), 'LINES TOUCHED'],
    [String(stats.agents.length), 'AGENTS ON DECK'],
    [stats.aiShare + '%', 'AI SHARE']
  ];
  statDefs.forEach(function (s, i) {
    const x = 40 + i * 185;
    p.push('<text x="' + x + '" y="126" font-size="24" font-weight="700" fill="' + t.accent + '">' + esc(s[0]) + '</text>');
    p.push('<text x="' + x + '" y="146" font-size="10" letter-spacing="1.5" fill="' + t.muted + '">' + esc(s[1]) + '</text>');
  });
  p.push('<line x1="40" y1="168" x2="760" y2="168" stroke="' + t.rule + '"/>');

  p.push('<text x="40" y="192" font-size="11" font-weight="700" letter-spacing="2" fill="' + t.muted + '">PERFORMANCE REVIEW</text>');

  const rowH = 40;
  agents.forEach(function (a, i) {
    const y = 212 + i * rowH;
    const color = COLOR_BY_ID[a.id] || t.accent;
    p.push('<circle cx="48" cy="' + (y - 4) + '" r="5" fill="' + color + '"/>');
    p.push('<text x="62" y="' + y + '" font-size="13" font-weight="600" fill="' + t.ink + '">' + esc(trunc(a.name, 18)) + '</text>');
    p.push('<text x="62" y="' + (y + 15) + '" font-size="10" fill="' + t.muted + '">' + esc(fmt(a.commits) + ' commits · +' + fmt(a.insertions) + ' −' + fmt(a.deletions) + ' · ' + fmt(a.files) + ' files') + '</text>');
    const bw = Math.max(4, Math.round(a.share * 250));
    p.push('<rect x="420" y="' + (y - 11) + '" width="250" height="8" rx="4" fill="' + t.surface + '"/>');
    p.push('<rect x="420" y="' + (y - 11) + '" width="' + bw + '" height="8" rx="4" fill="' + color + '"/>');
    const g = GRADE_COLORS[a.grade] || GRADE_COLORS.C;
    p.push('<rect x="692" y="' + (y - 14) + '" width="44" height="22" rx="6" fill="' + g + '" fill-opacity="0.12" stroke="' + g + '"/>');
    p.push('<text x="714" y="' + (y + 2) + '" font-size="12" font-weight="700" fill="' + g + '" text-anchor="middle">' + a.grade + '</text>');
  });

  p.push('<text x="40" y="406" font-size="11" font-weight="700" letter-spacing="2" fill="' + t.muted + '">ACTIVITY · LAST ' + stats.weeks.length + ' WEEKS</text>');
  p.push('<rect x="648" y="398" width="8" height="8" rx="2" fill="' + t.accent2 + '"/>');
  p.push('<text x="660" y="406" font-size="10" fill="' + t.muted + '">AI</text>');
  p.push('<rect x="684" y="398" width="8" height="8" rx="2" fill="' + t.muted + '" fill-opacity="0.35"/>');
  p.push('<text x="696" y="406" font-size="10" fill="' + t.muted + '">human</text>');

  const base = 452;
  const maxH = 32;
  const wk = stats.weeks;
  const maxTotal = Math.max.apply(null, [1].concat(wk.map(function (w) { return w.ai + w.human; })));
  const slot = wk.length > 0 ? 700 / wk.length : 1;
  const barW = Math.max(3, Math.min(16, slot * 0.6));
  wk.forEach(function (w, i) {
    const x = 45 + i * slot;
    const hH = Math.round((w.human / maxTotal) * maxH);
    const hA = Math.round((w.ai / maxTotal) * maxH);
    if (hH > 0) p.push('<rect x="' + x.toFixed(1) + '" y="' + (base - hH) + '" width="' + barW.toFixed(1) + '" height="' + hH + '" rx="1.5" fill="' + t.muted + '" fill-opacity="0.35"/>');
    if (hA > 0) p.push('<rect x="' + x.toFixed(1) + '" y="' + (base - hH - hA) + '" width="' + barW.toFixed(1) + '" height="' + hA + '" rx="1.5" fill="' + t.accent2 + '"/>');
  });
  p.push('<line x1="40" y1="' + (base + 0.5) + '" x2="760" y2="' + (base + 0.5) + '" stroke="' + t.rule + '"/>');

  p.push('<text x="40" y="470" font-size="10" fill="' + t.muted + '">generated by agentsume · ' + String(stats.generatedAt).slice(0, 10) + '</text>');
  p.push('<text x="760" y="470" font-size="10" fill="' + t.muted + '" text-anchor="end">github.com/fzs356113-oss/agentsume</text>');

  p.push('</svg>');
  return p.join('\n');
}

module.exports = { renderCard, THEMES, GRADE_COLORS };
